




.build/nano328/src/LnProtocolSlave.cpp : src/LnProtocolSlave.ino
	@mkdir -p .build/nano328/src
	@echo [93msrc/LnProtocolSlave.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/nano328/src/LnProtocolSlave.cpp
	@true

