




.build/uno/src/ReadSerial.cpp : src/ReadSerial.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/ReadSerial.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/ReadSerial.cpp
	@true

