




.build/nano328/src/my485Slave02.cpp : src/my485Slave02.ino
	@mkdir -p .build/nano328/src
	@echo [93msrc/my485Slave02.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/nano328/src/my485Slave02.cpp
	@true

