#!/bin/bash

[[ "$1" == "" ]] && echo "Enter USB port: ttyUSB0, ttyUSB1, ...." && exit

device=/dev/ttyUSBx
device=$1

[[ ! -c "$device" ]] && echo "$device is NOT a character device" && exit
module='nano328'

CMD="ino build -m $module"; echo $CMD; eval $CMD;rCode=$?
[[ "$rCode" != "0" ]] && echo $rCode && exit

CMD="ino upload -p $device -m $module"; echo $CMD; eval $CMD;rCode=$?
# ino upload -p $device -m $module;rCode=$?
[[ "$rCode" != "0" ]] && echo $rCode && exit


CMD="ino serial -p $device"; echo $CMD; eval $CMD;rCode=$?
# ino serial -p $device;rCode=$?
[[ "$rCode" != "0" ]] && echo $rCode && exit


