




.build/nano328/src/SimpleModbusSlaveArduino.cpp : src/SimpleModbusSlaveArduino.ino
	@mkdir -p .build/nano328/src
	@echo [93msrc/SimpleModbusSlaveArduino.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/nano328/src/SimpleModbusSlaveArduino.cpp
	@true

