







	



.build/nano328/RS485_protocol/RS485_non_blocking.d : /usr/share/arduino/libraries/RS485_protocol/RS485_non_blocking.cpp
	@mkdir -p .build/nano328/RS485_protocol
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/RS485_protocol -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Servo  -MM $^ > $@
	
	@printf ".build/nano328/RS485_protocol/RS485_non_blocking.d .build/nano328/RS485_protocol/" | cat - $@ > $@~ && mv $@~ $@

.build/nano328/RS485_protocol/RS485_protocol.d : /usr/share/arduino/libraries/RS485_protocol/RS485_protocol.cpp
	@mkdir -p .build/nano328/RS485_protocol
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/RS485_protocol -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Servo  -MM $^ > $@
	
	@printf ".build/nano328/RS485_protocol/RS485_protocol.d .build/nano328/RS485_protocol/" | cat - $@ > $@~ && mv $@~ $@



.build/nano328/RS485_protocol/dependencies.d : .build/nano328/RS485_protocol/RS485_non_blocking.d .build/nano328/RS485_protocol/RS485_protocol.d
	@echo [96mScanning dependencies of RS485_protocol[0m
	@mkdir -p .build/nano328/RS485_protocol
	@cat $^ > $@;

all : .build/nano328/RS485_protocol/dependencies.d
	@true

