




.build/nano328/src/my485Slave.cpp : src/my485Slave.ino
	@mkdir -p .build/nano328/src
	@echo [93msrc/my485Slave.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/nano328/src/my485Slave.cpp
	@true

