




.build/nano328/src/my485Master.cpp : src/my485Master.ino
	@mkdir -p .build/nano328/src
	@echo [93msrc/my485Master.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/nano328/src/my485Master.cpp
	@true

