




.build/nano328/src/LnProtocolMaster.cpp : src/LnProtocolMaster.ino
	@mkdir -p .build/nano328/src
	@echo [93msrc/LnProtocolMaster.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/nano328/src/LnProtocolMaster.cpp
	@true

