




.build/nano328/src/IAmArduino.cpp : src/IAmArduino.ino
	@mkdir -p .build/nano328/src
	@echo [93msrc/IAmArduino.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/nano328/src/IAmArduino.cpp
	@true

