




.build/nano328/src/modBusMaster.cpp : src/modBusMaster.ino
	@mkdir -p .build/nano328/src
	@echo [93msrc/modBusMaster.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/nano328/src/modBusMaster.cpp
	@true

